apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev
spec:
  selector:
    app: demo-frontend